import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react';

const API_URL = 'http://localhost:8010/api/getcommonsstudents';
const emailReg = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;

function _loadStudentRow (stu) {
  return <tr key={stu.studentId}>
    <th scope="row">{stu.studentId}</th>
    <td>{stu.email}</td>
    <td>{stu.createdAt}</td>
  </tr>
}

function getTutorEmailQuery(rawVal) {
  return rawVal.split(' ')
    .filter((isEmail) => emailReg.test(isEmail))
    .reduce((pv, email) => {
      if (pv) {
        pv += '&tutor=' + email
      } else {
        pv = 'tutor=' + email
      }

      return pv;
    }, null);
}

export async function getStaticProps() {
  try {
    const res = await axios.get(API_URL)

    const students = res.data?.students || [];

    return { props: { students } }
  } catch (e) {
    return { props: { students: [] } }
  }
}

export default function Home({ students }) {
  const [studentsData, setData] = useState(students);

  const onClick = async (event) => {
    event.preventDefault()
    try {
      const inputVal = event.target[0].value;
      const tutors = getTutorEmailQuery(inputVal);
      const apiUrl = API_URL + '?' + tutors;
      const res = await axios.get(apiUrl)
      if (res.status < 300) {
        const s = res.data?.students || []
        setData(s)
      }
    } catch (err) {
      setData([])
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Common Students
        </h1>
        <div>

        </div>
        <div className="container">
          <div className="col-md">
            <form onSubmit={onClick}>
              <div className="input-group mb-3">
                  <input type="text" id="tutorEmails" name="tutorEmails" className="form-control" placeholder="Tutor emails" aria-label="Tutor emails" aria-describedby="basic-addon2"></input>
                  <div className="input-group-append">
                    <button className="btn btn-outline-secondary" type="submit">Button</button>
                  </div>
              </div>
            </form>
          </div>
          <table className="table table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Date Registered</th>
              </tr>
            </thead>
            <tbody>
              {
                studentsData.map(_loadStudentRow)
              }
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
